name: Build and Push Docker Image
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  buildAndPushDockerImage:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    steps:
    - name: Set up QEMU for Docker Buildx
      uses: docker/setup-qemu-action@v3.0.0
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.3.0
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Build and push Docker images
      uses: docker/build-push-action@v5.1.0
      with:
        push: true
        tags: ${{ vars.DOCKER_IMAGE || github.repository }}:latest
        platforms: linux/arm64,linux/amd64
